version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 1316:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
        # named volume: postgres_data:/var/lib/postgresql/data/
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db

volumes:
    postgres_data:
